### ISSUE TITLE
Альфа-БК Monitor ROM

### ISSUE THREAD

**Issue by BrettHallen** [aleksey-f-morozov/retro_computers#1]
Hi,
I've dumped the КС573РФ2 EPROM on my Alpha-BK.  There are slight differences in it compared to the Radio-86RK ROM.  Maybe it is useful.
Brett.

My video related to this:
https://youtu.be/qnfDnGsyMwg

[ALPHA_BK_MONITOR.ROM.zip](https://github.com/alemorf/retro_computers/files/15442288/ALPHA_BK_MONITOR.ROM.zip)

**Comment by alemorf** [comment]
Saved to the repository

**Comment by BrettHallen** [comment]
Thank you sir!
