### ISSUE TITLE
Этот репозиторий невозможно использовать на Windows

### ISSUE THREAD

**Issue by intorr** [aleksey-f-morozov/retro_computers#2]
В этом репозитории присутствуют два файла:
Partner_01_01/firmware/lpt1.rkp
Partner_01_01/firmware/lpt2.rkp
Их названия являются зарезервированными для Windows и поэтому git не даёт сделать для них checkout.
Это описано, например, здесь:
https://learn.microsoft.com/ru-ru/windows/win32/fileio/naming-a-file

При git clone:

Cloning into 'retro_computers'...
remote: Enumerating objects: 11628, done.
remote: Counting objects: 100% (2405/2405), done.
remote: Compressing objects: 100% (1438/1438), done.
remote: Total 11628 (delta 933), reused 2371 (delta 908), pack-reused 9223
Receiving objects: 100% (11628/11628), 1.39 GiB | 4.19 MiB/s, done.
Resolving deltas: 100% (2984/2984), done.
error: invalid path 'Partner_01_01/firmware/lpt1.rkp'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

При git checkout:

error: invalid path 'Partner_01_01/firmware/lpt1.rkp'
error: invalid path 'Partner_01_01/firmware/lpt2.rkp'

Можешь ли ты переименовать эти файлы, например, добавив в конце названия подчёркивание?

**Comment by alemorf** [comment]
переименовал

**Comment by intorr** [comment]
Спасибо, теперь всё клонируется.

Однако есть ещё предупреждение из-за того, что у двух файлов одинаковые расширения в разном регистре:

Cloning into 'retro_computers'...
remote: Enumerating objects: 11632, done.
remote: Counting objects: 100% (2409/2409), done.
remote: Compressing objects: 100% (1442/1442), done.
remote: Total 11632 (delta 934), reused 2372 (delta 908), pack-reused 9223
Receiving objects: 100% (11632/11632), 1.39 GiB | 4.24 MiB/s, done.
Resolving deltas: 100% (2985/2985), done.
Updating files: 100% (12909/12909), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'Iskra_1080_Tartu/my_software/tetris_for_iskra_1080/graph_sources/plane.H'
  'Iskra_1080_Tartu/my_software/tetris_for_iskra_1080/graph_sources/plane.h'

Причём, судя по всему, в проекте используется файл plane.h который в нижнем регистре.

В целом это уже не мешает пользоваться репозиторием, но если захочешь, можешь и это поправить.
