### ISSUE TITLE
Partner 01.01 WAV files from RKP not working

### ISSUE THREAD

**Issue by BrettHallen** [aleksey-f-morozov/retro_computers#3]
Hi,
I've been trying to load WAV files onto my Partner using the BIN2WAV.C, compiled on my Mac for MacOS with no luck.  It seems the generated RKP -> WAV files are missing the header.  But I've been provided with some original WAV files that I can confirm are working (tried the TPP2 test program from the original cassette) if you wanted to add them to the software section (thanks to Peter G. for supplying them to me).
Brett.
[Partner_01_01_WAV.zip](https://github.com/user-attachments/files/16046953/Partner_01_01_WAV.zip)

**Comment by BrettHallen** [comment]
Dum da dum dum ... just this Westerner not fully understanding how to load files on the Partner - there's two methods: use the [R] command to load files in "MSX format" (i.e. that have a header) or the RK Monitor method of [I] when it is straight data.  But maybe it would be handy to have a copy of the original Partner cassette files - I will open a new Issue if that's useful.

**Comment by alemorf** [comment]
Thank you. I have add this file to the repository.
